// Generated by CoffeeScript 1.4.0
(function() {
  var mrtData;

  mrtData = function() {
    return console.log('here');
  };

  google.load("gdata", "2.x");

  google.setOnLoadCallback(mrtData);

}).call(this);
