// Generated by CoffeeScript 1.4.0
(function() {
  var G, addOverlay, centerPoint, getTileNumbers, load, zoom;

  G = google.maps;

  zoom = 4;

  centerPoint = new G.LatLng(40.178873, -96.767578);

  load = function() {
    var container, map, myOptions;
    container = document.getElementById('mapContainer');
    myOptions = {
      zoom: zoom,
      center: centerPoint,
      mapTypeId: G.MapTypeId.ROADMAP
    };
    map = new G.Map(container, myOptions);
    if (typeof shareBox === 'function') {
      shareBox();
    }
    return G.event.addListener(map, 'drag', getTileNumbers);
  };

  getTileNumbers = function() {
    var bounds, nLat, proj, sLat;
    proj = map.getProjection();
    bounds = map.getBounds();
    sLat = map.getBounds().getSouthWest().lat();
    nLat = map.getBounds().getNorthEast().lat();
    if (sLat < -85 || nLat > 85) {
      return debug('Gray area visible');
    }
  };

  addOverlay = function(theme) {
    var hMap, oDiv, tlc, tlcOptions;
    hMap = new MCustomTileLayer(map, theme);
    oDiv = document.getElementById('controlsContainer');
    tlcOptions = {
      parent: oDiv,
      overlay: hMap,
      caption: theme.toUpperCase()
    };
    return tlc = new MTileLayerControl(tlcOptions);
  };

  window.onload = load;

}).call(this);
